<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Histories_nav-link nav-link-lg</name>
   <tag></tag>
   <elementGuidId>dfcd0b45-a438-4802-8458-04988f633314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.nav-link-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/nav/form/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9347063-d46c-405d-865c-bd471b3d2bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5de9ead1-1135-4c49-a1cc-fbbe00859306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>sidebar</value>
      <webElementGuid>34a214e6-3d56-442c-a08d-e4d7b225cab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link nav-link-lg</value>
      <webElementGuid>fde49e38-8ae2-434b-9cf2-731c1ac061b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-wrapper&quot;]/nav[@class=&quot;navbar navbar-expand-lg main-navbar&quot;]/form[@class=&quot;form-inline mr-auto&quot;]/ul[@class=&quot;navbar-nav mr-3&quot;]/li[1]/a[@class=&quot;nav-link nav-link-lg&quot;]</value>
      <webElementGuid>ebf8c341-0285-49e9-a9e4-2a050d3f1e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d07f28d-a436-4e41-b808-8f3fe874047a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9edf64a1-ff2d-4ee8-8ee4-3e1d0c1fe655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>sidebar</value>
      <webElementGuid>87410da5-d764-4d79-b378-2529f6c662f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link nav-link-lg</value>
      <webElementGuid>4c10842d-6c0b-4e1a-b1fc-0397fcd88280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-wrapper&quot;]/nav[@class=&quot;navbar navbar-expand-lg main-navbar&quot;]/form[@class=&quot;form-inline mr-auto&quot;]/ul[@class=&quot;navbar-nav mr-3&quot;]/li[1]/a[@class=&quot;nav-link nav-link-lg&quot;]</value>
      <webElementGuid>d3fb482f-398e-4873-b236-b4baddb682d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/nav/form/ul/li/a</value>
      <webElementGuid>a9a2d27f-c6df-4828-8897-fba02eff1b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Histories'])[1]/preceding::a[2]</value>
      <webElementGuid>20607894-17c1-4566-88d8-c978b703a6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result'])[1]/preceding::a[8]</value>
      <webElementGuid>c65ff8a9-5442-4ab7-8a6e-80269b3174b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>f215f3a3-b476-4eb9-bccd-b089d80dac75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7134699d-57ec-4d51-b8f4-cd8e1de6077a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>8c0cdab4-d6fb-47eb-b732-84024a9a9519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
